#!/usr/bin/env bash
# Stage II step: push the *.avsc schema files (generated by Sqoop in
# Stage I) into HDFS so the Hive EXTERNAL tables can reference them via
# avro.schema.url. Idempotent: -put -f overwrites.
set -euo pipefail

TEAM="team1"
HDFS_AVSC_DIR="/user/${TEAM}/project/warehouse/avsc"

if ! ls output/*.avsc >/dev/null 2>&1; then
    echo "ERROR: no output/*.avsc files found — run scripts/data_ingestion.sh first" >&2
    exit 1
fi

hdfs dfs -mkdir -p "$HDFS_AVSC_DIR"
hdfs dfs -put -f output/*.avsc "$HDFS_AVSC_DIR/"

echo "[upload_avsc] HDFS contents of $HDFS_AVSC_DIR:"
hdfs dfs -ls "$HDFS_AVSC_DIR"
